[build]
builder = "RAILPACK"
# Setting the install command to true effectively skips the install step
RAILPACK_INSTALL_CMD = "true"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx serve -s dist -l $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
